### ISSUE TITLE
Distinguish between continuous and incremental inputs

### ISSUE THREAD

**Issue by JRitmeester** [JRitmeester/WaVeS#32]
Based on #29 

**Is your feature request related to a problem? Please describe.**
Sliders/potentiometers have a continuous value that can be sent every cycle to WaVeS. For potentiometers or buttons, no absolute value is available unless a the microcontroller would receive feedback from the application, we has been shown to create race conditions for such timing-sensitive operations.

**Describe the solution you'd like**
A way to configure a given input index to be a relative or absolute input device. This means that for a relative input device, the received value from the serial connection is the desired difference in volume, not the desired target volume.

**Describe alternatives you've considered**
An attempt was made to create a feedback system to sync the microcontroller about the volume values, but this got cumbersome and unreliable.

**Proposed Implementation**
When reading the serial inputs, it should look for each value if it's a relative value and add this value (which can also be negative).

**Configuration Changes**
Example of `mapping.yml`:
```yaml
...
mappings:
  0:  # Keep this as a slider
    assign: 
      - master
    input_type: absolute  # Would also be the default behaviour if not explicitly specified

  1:  # Make this a relative input like an encoder
    assign:
      - system
    input_type: relative

device:
  sliders: 2
...
```

**Additional context**
This does not yet support muting, for which an additional type of message should be created. One that is not a number, like "mute" and "unmute".

**Priority**
- [ ] High (Blocks my workflow)
- [x] Medium (Would be nice to have)
- [ ] Low (Not urgent, but would be useful)
